apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cp-db2wh-my-module
spec:
  destination:
    namespace: gitops-cp-db2wh
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/gitops-cp-db2wh/my-module
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-cp-db2wh
    targetRevision: my-module-payload
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
